In [101]:
import numpy as np

In [102]:
inputs = np.array([[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]])
weights = np.array([[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]])
biases = np.array([2,3,0.5])

In [103]:
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer1_outputs

array([[ 4.79999995,  1.21000004,  2.38499999],
       [ 8.9000001 , -1.80999994,  0.19999999],
       [ 1.41000003,  1.051     ,  0.02599999]])

In [104]:
# layer_1 outputs become inputs for layer_2
weights2 = [[0.1,-0.14,0.5],[-0.5,0.12,-0.33],[-0.44,0.73,-0.13]]
biases2 = [-1,2,-0.5]

In [105]:
layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases
layer2_outputs

array([[ 3.50310004, -0.04184985, -1.03874993],
       [ 3.24339998, -1.73320007, -4.76329994],
       [ 2.00686   ,  2.41254002,  0.64344999]])

In [106]:
np.random.seed(0)   # reproduce same results everytime

X = np.array([[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]])

In [107]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # get same value of weights each time running the code
        self.biases = np.zeros((1, n_neurons))
    
    def forward(self,inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [108]:
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
layer1.output

array([[ 0.10758132,  1.0398352 ,  0.2446241 ,  0.31821495,  0.18851054],
       [-0.08349796,  0.70846415,  0.00293357,  0.44701523,  0.3636054 ],
       [-0.50763243,  0.5568842 ,  0.07987796, -0.34889573,  0.04553042]],
      dtype=float32)

In [109]:
layer2.forward(layer1.output)
layer2.output

array([[ 0.148296  , -0.08397602],
       [ 0.14100316, -0.01340469],
       [ 0.20124978, -0.07290616]], dtype=float32)

## Activation Functions

### Rectified Linear Function (ReLU)

In [110]:
x = np.array([[1,2,3,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]])

In [111]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []

In [112]:
for i in inputs:
    output.append(max(0,i))  
output    

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

In [113]:
class Activation_ReLU:
    def forward(self, inputs):
       self.output = np.maximum(0, inputs) 

In [114]:
layer1.forward(x)
layer1.output

array([[ 0.10758132,  1.0398352 ,  0.2446241 ,  0.31821495,  0.18851054],
       [-0.08349796,  0.70846415,  0.00293357,  0.44701523,  0.3636054 ],
       [-0.50763243,  0.5568842 ,  0.07987796, -0.34889573,  0.04553042]],
      dtype=float32)

In [115]:
activation1 = Activation_ReLU()

In [116]:
activation1.forward(layer1.output)
activation1.output

array([[0.10758132, 1.0398352 , 0.2446241 , 0.31821495, 0.18851054],
       [0.        , 0.70846415, 0.00293357, 0.44701523, 0.3636054 ],
       [0.        , 0.5568842 , 0.07987796, 0.        , 0.04553042]],
      dtype=float32)

### Softmax Activation

Input -> Exponentiate -> Normalize -> Output

Exponentiate and Normalize together is softmax


In [117]:
!pip install nnfs

In [118]:
import math
import nnfs

In [119]:
nnfs.init()

In [120]:
layer_outputs = [4.8, 1.21, 2.385]

In [121]:
E = math.e
E

2.718281828459045

In [122]:
exp_values = np.exp(layer_outputs)
exp_values

array([121.51041752,   3.35348465,  10.85906266])

In [123]:
norm_values = exp_values / np.sum(exp_values)
norm_values

array([0.89528266, 0.02470831, 0.08000903])

In [124]:
np.sum(norm_values)

0.9999999999999999

#### Work as a batch

In [125]:
layer_outputs = [[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

In [126]:
exp_values = np.exp(layer_outputs)
exp_values

array([[1.21510418e+02, 3.35348465e+00, 1.08590627e+01],
       [7.33197354e+03, 1.63654137e-01, 1.22140276e+00],
       [4.09595540e+00, 2.86051020e+00, 1.02634095e+00]])

In [127]:
norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
norm_values

array([[8.95282664e-01, 2.47083068e-02, 8.00090293e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [128]:
np.sum(norm_values)

3.0

In [129]:
class Activation_Softmax:
    def forward(self, inputs):
       exp_values =  np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
       probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
       self.output = probabilities   

In [130]:
from nnfs.datasets import spiral_data

In [131]:
X, y = spiral_data(samples=100, classes=3)

In [132]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

In [133]:
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

In [134]:
dense1.forward(X)
activation1.forward(dense1.output)

In [135]:
dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [136]:
activation2.output[:5]

array([[0.33333334, 0.33333334, 0.33333334],
       [0.33331734, 0.3333183 , 0.33336434],
       [0.3332888 , 0.33329153, 0.33341965],
       [0.33325943, 0.33326396, 0.33347666],
       [0.33323312, 0.33323926, 0.33352762]], dtype=float32)

## Categorical Cross-Entropy

In [137]:
softmax_output = [0.7, 0.1, 0.2]
target_output = [1,0,0]

loss = -(math.log(softmax_output[0])*target_output[0] + math.log(softmax_output[1])*target_output[1] + math.log(softmax_output[2])*target_output[2])
loss

0.35667494393873245

In [138]:
softmax_outputs = np.array([[0.7,0.1,0.2],[0.1,0.5,0.4],[0.02,0.9,0.08]])
class_targets = [0, 1, 1]
softmax_outputs[[0,1,2], class_targets]

array([0.7, 0.5, 0.9])

In [139]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [144]:
class Loss_CategoricalCrossEntropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples)]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
            
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods

In [145]:
loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)
loss

1.0986278