In [1]:
import torch

In [2]:
torch.__version__

'2.3.0'

In [3]:
import numpy as np

In [20]:
lst = [3,4,5,6]
arr = np.array(lst)
arr

array([3, 4, 5, 6])

In [5]:
arr.dtype

dtype('int32')

### Convert Numpy to Pytorch Tensors

In [6]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [7]:
tensors[3] = 100
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [8]:
arr

array([  3,   4,   5, 100])

In [10]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [12]:
tensor_arr[3] = 120
tensor_arr

tensor([  3,   4,   5, 120], dtype=torch.int32)

In [13]:
arr

array([  3,   4,   5, 100])

In [14]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [16]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [19]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

###### Airthmetic operations

In [23]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [28]:
torch.add(a,b).sum()

tensor(27.)

In [25]:
c = torch.zeros(3)

In [26]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [27]:
c

tensor([ 7.,  9., 11.])

##### Dot product and Multi operations

In [29]:
a.mul(b)

tensor([12., 20., 30.])

In [30]:
a.dot(b)

tensor(62.)

In [32]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [33]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [34]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [35]:
x@y

tensor([[55., 53.],
        [90., 92.]])

##### Back Propogation using Pytorch

Back Propogation --- compute derivatives

y = x^2

In [36]:
x = torch.tensor(4.0,requires_grad=True)

In [37]:
x

tensor(4., requires_grad=True)

In [38]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [39]:
##### Back propogation y=2*x
y.backward()

In [40]:
print(x.grad)

tensor(8.)


In [44]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst,requires_grad=True)

In [45]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [49]:
# y = x**3+x**2
# y = 3x**2+2*x
y = torch_input**3+torch_input**2

In [50]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [51]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [62]:
z.backward(retain_graph=True)
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [63]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])